name: Playwright Tests

# This workflow will run whenever code is pushed to the repository or a pull request is opened.
on:
  push:
    branches:
      - main  # Change to the default branch of your repository
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Node.js versions and Playwright browsers you want to test against
        node-version: [16.x]
        browser: [chromium, firefox, webkit]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Playwright dependencies
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests for the specified browser
      - name: Run Playwright tests
        run: |
          npx playwright test --browser ${{ matrix.browser }}

      # Step 6: Upload Playwright report (optional)
      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report/
